language: node_js
cache: yarn
node_js:
- '11'
script:
- npm i bs-platform
- npm run build
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
    repo: ryb73/bs-scrypt
  api_key:
    secure: nJfcapDKAQIxHMLjS/kvIIjUdE24zrGA2VyB7RtR4iSSomSjfWK4ZcEahkRbLzbUlfM2hM3No6n1JtTZaI+wMtbkrlcU0dVAQHFgFVlcRJUQ1vMehLD+5cV6aVPiHguaimoiZn/1HZLaDvHBnl6OHOIuZ6cb7B0iMEigeqxfAjE9FSd1V/WnYCz8QAepX4MJY9QVkMZ/PPMxsomecZUCwi6o2ERlzCNC7j6gYVx/ZOi1fhaeiEcfbpkZEeawvdCwqDpQEtMIlDeCFRzpRzRq1MmBjeRg6AfqUMSs2I/XoghCRwpGuN3H1fjXpyeDsFgIzNiwqS6nqGH2Otj9nbprkMb8we4BHKGTAH9K4P1drNIjd3CQGQCEo7gbE9qTo3qCCTVEQflY1MuQZ2lBqyR0CcMykISbuznj7SsWw709i4Lx0WD9mwXLHe/d+NQhYtfsamGFSlZesLQxfsanUiVw7mgcI0lbEx4vg4veSOTkrjWr8rQkF13eeZgai6kXUYMrbK5Vtcw5una+XXbxVIiHsWDMCCC1mGLjE6ld72zeynqHVDKYhv6Fz/F0JA+gFH3Ty7EFwhyM/RwTjSUWtAYTuSg9r6A6w0aju37PE6Msk9kBwQQ7tOZfkrCHxel/KJgQDae4MjKF/FbOdnwP5hDnnjIt3VUDZNSWWS0MFmR5Dzw=
