language: node_js
cache: yarn
node_js:
- '11'
script:
- npm i bs-platform
- npm run build
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: Nygul9J+B80pZZ0jVDi41s7OQH1c5fVHHEvlw6GnYxwuAuG1lRvQllFxNNIFcesElps4o043bW0z/MtUwkKaLFxAbvPnDJimYJosyWN80OqZpennJlvnJo3Rqr+mdoOkBQrr0WmpdQZ2ixul0A0FkpVg+JS/K0nhUR7MAKqElo7GVTWdq/4Bxqql3sDMT/DJYr7ETZRrhG3uZToHgobC68NV0yUh74GaElbKSfsDTFtICln/DU+WeL+aBPVVdE4fJ1kfRqv4z6o+zVxu4driLIS2sjVKnUvSjf2PcSzwqJ328GeBy6xm25HXa9RetR6Wz2FUDFxM0mfjzogIuOT0//PSiGDJrL2VomRP1nhbe19CBF2JIReZG6bjgh7dL5pM0I4f6iWr8Zu3YIvBn2sqSOWTqHo61bTT4zYay1jea8ZKhTrCtlVYv718Qo9QToHnGHCUtNB9RHhFw+CLAI1u3HRtR4EO1ky1iAnZ6n+AMjOvoqgvYWrdSV6C8vGZdfawAnJd6XIBjLjkWgWcN4DTkP13zvLe7NdgUAkNOuQZzxn4br65gJlwupuJLt+TIGiX/a7eqyeTRrWBVtquBNdBP/5ofLia6OXbfUAbWYa09lc7MlnlLy8aL+K/gjzqe5aZ406pSWvUDDFd8I7I9NrE4Z10SyI926qMWtowWiflVk0=
